name: Daily Food Price Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dbt-postgres

      - name: Run Python ingestion script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python ingest_data.py

      - name: Run dbt models
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          cd food_prices
          dbt run --profiles-dir .